#!/usr/bin/env python3
"""Distributed training for the evaluator-aligned CVA joint utility scorer.

The base EconomicGrasp-DPT/CVA network is not instantiated here. Candidate
features and exact evaluator labels are loaded from the cache generated by the
joint-utility miner.

Important integration detail
----------------------------
Some EconomicGrasp packages import ``utils.arguments`` from their package
``__init__`` files. That module parses ``sys.argv`` at import time. Therefore
this script must consume and remove its own ``--cache_dir``, ``--output_dir``,
and scorer-specific arguments *before* importing any project-local package.
Otherwise the legacy EconomicGrasp parser sees these arguments and exits with
"unrecognized arguments".
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
import sys
import time
from dataclasses import asdict
from typing import Any, Dict, Mapping, Optional, Tuple

import numpy as np
import torch
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader, DistributedSampler, Subset


_TRAIN_ARGS_ENV = "CVA_JOINT_UTILITY_TRAIN_ARGS_JSON"


def _build_joint_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Train the frozen-feature evaluator-aligned CVA joint utility scorer."
    )
    # Do not mark these required at construction time: multiprocessing spawn may
    # re-import this module with a sanitized argv. main() validates them instead.
    p.add_argument("--cache_dir", default="")
    p.add_argument("--output_dir", default="")
    p.add_argument("--val_scene_start", type=int, default=90)
    p.add_argument("--epochs", type=int, default=30)
    p.add_argument("--batch_size", type=int, default=2, help="Frames per GPU, not candidates.")
    p.add_argument("--num_workers", type=int, default=4)
    p.add_argument("--max_candidates_per_sample", type=int, default=2048)
    p.add_argument("--keep_hard_negatives", type=int, default=512)
    p.add_argument("--keep_positives", type=int, default=512)
    p.add_argument("--keep_per_center", type=int, default=1)
    p.add_argument("--max_train_files", type=int, default=-1)
    p.add_argument("--max_val_files", type=int, default=-1)
    p.add_argument("--lr", type=float, default=2e-4)
    p.add_argument("--min_lr", type=float, default=1e-6)
    p.add_argument("--warmup_epochs", type=float, default=1.0)
    p.add_argument("--weight_decay", type=float, default=1e-4)
    p.add_argument("--grad_clip", type=float, default=5.0)
    p.add_argument("--grad_accum_steps", type=int, default=1)
    p.add_argument("--amp", type=int, default=1)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--resume", default="")
    p.add_argument("--save_every", type=int, default=1)
    p.add_argument("--log_every", type=int, default=20)
    p.add_argument("--best_metric", default="metric/evaluator_proxy_ap")
    p.add_argument("--best_mode", choices=["max", "min"], default="max")

    # Scorer architecture.
    p.add_argument("--hidden_dim", type=int, default=256)
    p.add_argument("--aux_hidden_dim", type=int, default=128)
    p.add_argument("--num_residual_blocks", type=int, default=3)
    p.add_argument("--dropout", type=float, default=0.10)
    p.add_argument("--max_view_rank", type=int, default=8)
    p.add_argument("--disable_legacy_collision_input", action="store_true")
    p.add_argument("--disable_geometry", action="store_true")
    p.add_argument("--disable_view_score", action="store_true")
    p.add_argument("--disable_monotonic_cdf", action="store_true")

    # Loss weights.
    p.add_argument("--cdf_weight", type=float, default=1.0)
    p.add_argument("--utility_weight", type=float, default=0.25)
    p.add_argument("--collision_weight", type=float, default=0.15)
    p.add_argument("--empty_weight", type=float, default=0.10)
    p.add_argument("--center_rank_weight", type=float, default=0.50)
    p.add_argument("--object_rank_weight", type=float, default=0.35)
    p.add_argument("--sample_rank_weight", type=float, default=0.25)
    p.add_argument("--listwise_weight", type=float, default=0.15)
    p.add_argument("--hard_negative_weight", type=float, default=1.5)
    p.add_argument("--hard_negative_quality_threshold", type=float, default=0.75)
    p.add_argument("--rank_margin", type=float, default=0.10)
    p.add_argument("--rank_target_gap", type=float, default=1.0 / 6.0)
    p.add_argument("--listwise_temperature", type=float, default=0.20)
    p.add_argument("--unbalanced_cdf", action="store_true")
    p.add_argument("--unbalanced_aux", action="store_true")

    # Older torch.distributed.launch may inject this command-line option. New
    # torchrun normally uses LOCAL_RANK in the environment, but accepting both
    # spellings keeps the parser robust.
    p.add_argument("--local-rank", "--local_rank", type=int, default=None, help=argparse.SUPPRESS)
    return p


def _consume_joint_args_before_project_imports() -> Tuple[argparse.Namespace, list[str]]:
    parser = _build_joint_parser()
    raw = sys.argv[1:]

    if raw:
        args, unknown = parser.parse_known_args(raw)
        # Preserve the parsed values for a possible multiprocessing-spawn
        # re-import, where argv may already have been sanitized.
        os.environ[_TRAIN_ARGS_ENV] = json.dumps(vars(args), sort_keys=True)
    else:
        payload = os.environ.get(_TRAIN_ARGS_ENV, "")
        if payload:
            args = argparse.Namespace(**json.loads(payload))
            unknown = []
        else:
            args, unknown = parser.parse_known_args([])

    # Critical: legacy utils.arguments must never see the joint-scorer flags.
    # Leave only arguments not owned by this script. main() later rejects any
    # unknown leftovers explicitly.
    sys.argv[:] = [sys.argv[0], *unknown]
    return args, list(unknown)


_PREPARSED_ARGS, _PREPARSED_UNKNOWN = _consume_joint_args_before_project_imports()

# Project-local imports must remain below the argv sanitation above.
from dataset.cva_joint_utility_cache import (  # noqa: E402
    CVAJointUtilityCacheDataset,
    CacheSamplingConfig,
    collate_joint_utility_cache,
    save_cache_inventory,
)
from models.cva_joint_utility import (  # noqa: E402
    EvaluatorAlignedJointUtilityScorer,
    JointUtilityScorerConfig,
)
from models.loss_cva_joint_utility import (  # noqa: E402
    JointUtilityLossConfig,
    compute_joint_utility_loss,
)


def parse_args() -> argparse.Namespace:
    parser = _build_joint_parser()
    if _PREPARSED_UNKNOWN:
        parser.error("unrecognized arguments: " + " ".join(_PREPARSED_UNKNOWN))
    args = argparse.Namespace(**vars(_PREPARSED_ARGS))
    if not str(args.cache_dir).strip():
        parser.error("the following argument is required: --cache_dir")
    if not str(args.output_dir).strip():
        parser.error("the following argument is required: --output_dir")
    return args


def init_distributed() -> Tuple[int, int, int, torch.device]:
    if "RANK" in os.environ and "WORLD_SIZE" in os.environ:
        dist.init_process_group(backend="nccl" if torch.cuda.is_available() else "gloo")
        rank = dist.get_rank()
        world = dist.get_world_size()
        local_rank = int(os.environ.get("LOCAL_RANK", 0))
    else:
        rank, world, local_rank = 0, 1, 0
    if torch.cuda.is_available():
        torch.cuda.set_device(local_rank)
        device = torch.device("cuda", local_rank)
    else:
        device = torch.device("cpu")
    return rank, world, local_rank, device


def is_main(rank: int) -> bool:
    return rank == 0


def seed_everything(seed: int, rank: int) -> None:
    value = int(seed) + int(rank) * 100003
    random.seed(value)
    np.random.seed(value)
    torch.manual_seed(value)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(value)


def worker_init_fn(worker_id: int) -> None:
    seed = torch.initial_seed() % (2**32)
    np.random.seed(seed + worker_id)
    random.seed(seed + worker_id)


def move_to_device(batch: Mapping[str, Any], device: torch.device) -> Dict[str, Any]:
    return {
        key: value.to(device, non_blocking=True) if torch.is_tensor(value) else value
        for key, value in batch.items()
    }


def make_datasets(args: argparse.Namespace):
    sampling = CacheSamplingConfig(
        max_candidates_per_sample=args.max_candidates_per_sample,
        keep_hard_negatives=args.keep_hard_negatives,
        keep_positives=args.keep_positives,
        keep_per_center=args.keep_per_center,
        seed=args.seed,
    )
    train = CVAJointUtilityCacheDataset(
        args.cache_dir,
        split="train",
        val_scene_start=args.val_scene_start,
        sampling=sampling,
    )
    val = CVAJointUtilityCacheDataset(
        args.cache_dir,
        split="val",
        val_scene_start=args.val_scene_start,
        sampling=sampling,
    )
    if args.max_train_files > 0:
        train = Subset(train, list(range(min(args.max_train_files, len(train)))))
    if args.max_val_files > 0:
        val = Subset(val, list(range(min(args.max_val_files, len(val)))))
    return train, val


def dataset_schema(dataset) -> Dict[str, int]:
    base = dataset.dataset if isinstance(dataset, Subset) else dataset
    return dict(base.schema)


def make_loader(dataset, args, rank: int, world: int, train: bool):
    sampler = None
    if world > 1:
        sampler = DistributedSampler(
            dataset, num_replicas=world, rank=rank, shuffle=train, drop_last=False
        )
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=(train and sampler is None),
        sampler=sampler,
        num_workers=args.num_workers,
        pin_memory=torch.cuda.is_available(),
        persistent_workers=args.num_workers > 0,
        worker_init_fn=worker_init_fn,
        collate_fn=collate_joint_utility_cache,
        drop_last=False,
    )
    return loader, sampler


def cosine_with_warmup(step: int, total_steps: int, warmup_steps: int, min_ratio: float) -> float:
    if warmup_steps > 0 and step < warmup_steps:
        return max(float(step + 1) / float(warmup_steps), 1e-4)
    progress = (step - warmup_steps) / max(total_steps - warmup_steps, 1)
    cosine = 0.5 * (1.0 + math.cos(math.pi * min(max(progress, 0.0), 1.0)))
    return min_ratio + (1.0 - min_ratio) * cosine


def reduce_metric_sums(sums: Dict[str, float], count: float, device: torch.device, world: int):
    keys = sorted(sums)
    values = torch.tensor([sums[k] for k in keys] + [count], device=device, dtype=torch.float64)
    if world > 1:
        dist.all_reduce(values, op=dist.ReduceOp.SUM)
    total_count = max(float(values[-1].item()), 1.0)
    return {k: float(values[i].item() / total_count) for i, k in enumerate(keys)}


def run_epoch(
    model: torch.nn.Module,
    loader: DataLoader,
    loss_cfg: JointUtilityLossConfig,
    device: torch.device,
    world: int,
    train: bool,
    optimizer: Optional[torch.optim.Optimizer],
    scheduler: Optional[torch.optim.lr_scheduler.LambdaLR],
    scaler: Any,
    args: argparse.Namespace,
    epoch: int,
    rank: int,
) -> Dict[str, float]:
    model.train(train)
    metric_sums: Dict[str, float] = {}
    metric_count = 0.0
    if train and optimizer is not None:
        optimizer.zero_grad(set_to_none=True)

    for batch_idx, batch_cpu in enumerate(loader):
        batch = move_to_device(batch_cpu, device)
        amp_enabled = bool(args.amp) and device.type == "cuda"
        with torch.set_grad_enabled(train), torch.amp.autocast(device_type=device.type, enabled=amp_enabled):
            outputs = model(batch)
            loss, metrics = compute_joint_utility_loss(outputs, batch, loss_cfg)
            scaled_loss = loss / max(int(args.grad_accum_steps), 1)

        if train:
            scaler.scale(scaled_loss).backward()
            do_step = ((batch_idx + 1) % max(int(args.grad_accum_steps), 1) == 0) or (
                batch_idx + 1 == len(loader)
            )
            if do_step:
                scaler.unscale_(optimizer)
                if args.grad_clip > 0:
                    torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad(set_to_none=True)
                if scheduler is not None:
                    scheduler.step()

        weight = float(int(batch["num_samples"].item()))
        metric_count += weight
        for key, value in metrics.items():
            scalar = float(value.detach().float().cpu().item())
            if math.isfinite(scalar):
                metric_sums[key] = metric_sums.get(key, 0.0) + scalar * weight
        if train and is_main(rank) and args.log_every > 0 and (batch_idx + 1) % args.log_every == 0:
            lr = optimizer.param_groups[0]["lr"] if optimizer is not None else 0.0
            print(
                f"[TRAIN] epoch={epoch:03d} iter={batch_idx+1:05d}/{len(loader):05d} "
                f"loss={float(loss.detach()):.4f} top10U={float(metrics['metric/top10_utility']):.4f} "
                f"invalid10={float(metrics['metric/top10_invalid']):.4f} lr={lr:.3e}",
                flush=True,
            )
    return reduce_metric_sums(metric_sums, metric_count, device, world)


def save_checkpoint(
    path: str,
    model: torch.nn.Module,
    optimizer: torch.optim.Optimizer,
    scheduler: torch.optim.lr_scheduler.LambdaLR,
    scaler: Any,
    epoch: int,
    best_value: float,
    scorer_cfg: JointUtilityScorerConfig,
    loss_cfg: JointUtilityLossConfig,
    schema: Mapping[str, int],
    args: argparse.Namespace,
) -> None:
    raw_model = model.module if isinstance(model, DDP) else model
    payload = {
        "epoch": int(epoch),
        "model_state_dict": raw_model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "scheduler_state_dict": scheduler.state_dict(),
        "scaler_state_dict": scaler.state_dict(),
        "best_value": float(best_value),
        "scorer_config": scorer_cfg.to_dict(),
        "loss_config": loss_cfg.to_dict(),
        "cache_schema": dict(schema),
        "args": vars(args),
    }
    tmp = f"{path}.tmp.{os.getpid()}"
    torch.save(payload, tmp)
    os.replace(tmp, path)


def append_history(path: str, row: Mapping[str, Any]) -> None:
    exists = os.path.isfile(path)
    keys = list(row.keys())
    with open(path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        if not exists:
            writer.writeheader()
        writer.writerow(row)


def main() -> None:
    args = parse_args()
    rank, world, local_rank, device = init_distributed()
    seed_everything(args.seed, rank)
    if is_main(rank):
        os.makedirs(args.output_dir, exist_ok=True)
        with open(os.path.join(args.output_dir, "train_args.json"), "w", encoding="utf-8") as f:
            json.dump(vars(args), f, indent=2)
    if world > 1:
        dist.barrier()

    train_set, val_set = make_datasets(args)
    schema = dataset_schema(train_set)
    if is_main(rank):
        base_train = train_set.dataset if isinstance(train_set, Subset) else train_set
        base_val = val_set.dataset if isinstance(val_set, Subset) else val_set
        save_cache_inventory(base_train, os.path.join(args.output_dir, "train_cache_inventory.json"))
        save_cache_inventory(base_val, os.path.join(args.output_dir, "val_cache_inventory.json"))
        print(f"[DATA] train_files={len(train_set)} val_files={len(val_set)} schema={schema}")

    scorer_cfg = JointUtilityScorerConfig(
        angle_feature_dim=schema["angle_feature_dim"],
        score_logit_dim=schema["score_logit_dim"],
        depth_logit_dim=schema["depth_logit_dim"],
        num_angles=schema["num_angles"],
        num_depths=schema["num_depths"],
        max_view_rank=max(args.max_view_rank, schema["max_view_rank"]),
        hidden_dim=args.hidden_dim,
        aux_hidden_dim=args.aux_hidden_dim,
        num_residual_blocks=args.num_residual_blocks,
        dropout=args.dropout,
        use_legacy_collision=not args.disable_legacy_collision_input,
        use_geometry=not args.disable_geometry,
        use_view_score=not args.disable_view_score,
        monotonic_cdf=not args.disable_monotonic_cdf,
    )
    loss_cfg = JointUtilityLossConfig(
        cdf_weight=args.cdf_weight,
        utility_weight=args.utility_weight,
        collision_weight=args.collision_weight,
        empty_weight=args.empty_weight,
        center_rank_weight=args.center_rank_weight,
        object_rank_weight=args.object_rank_weight,
        sample_rank_weight=args.sample_rank_weight,
        listwise_weight=args.listwise_weight,
        balanced_cdf=not args.unbalanced_cdf,
        balanced_aux=not args.unbalanced_aux,
        hard_negative_weight=args.hard_negative_weight,
        hard_negative_quality_threshold=args.hard_negative_quality_threshold,
        rank_margin=args.rank_margin,
        rank_target_gap=args.rank_target_gap,
        listwise_temperature=args.listwise_temperature,
    )

    model = EvaluatorAlignedJointUtilityScorer(scorer_cfg).to(device)
    if world > 1:
        model = DDP(model, device_ids=[local_rank] if device.type == "cuda" else None)

    train_loader, train_sampler = make_loader(train_set, args, rank, world, train=True)
    val_loader, val_sampler = make_loader(val_set, args, rank, world, train=False)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    updates_per_epoch = math.ceil(len(train_loader) / max(args.grad_accum_steps, 1))
    total_updates = max(1, args.epochs * updates_per_epoch)
    warmup_updates = int(args.warmup_epochs * updates_per_epoch)
    scheduler = torch.optim.lr_scheduler.LambdaLR(
        optimizer,
        lr_lambda=lambda step: cosine_with_warmup(
            step, total_updates, warmup_updates, args.min_lr / max(args.lr, 1e-12)
        ),
    )
    scaler = torch.amp.GradScaler("cuda", enabled=bool(args.amp) and device.type == "cuda")

    start_epoch = 0
    best_value = -float("inf") if args.best_mode == "max" else float("inf")
    if args.resume:
        checkpoint = torch.load(args.resume, map_location="cpu")
        raw_model = model.module if isinstance(model, DDP) else model
        raw_model.load_state_dict(checkpoint["model_state_dict"])
        optimizer.load_state_dict(checkpoint["optimizer_state_dict"])
        scheduler.load_state_dict(checkpoint["scheduler_state_dict"])
        if "scaler_state_dict" in checkpoint:
            scaler.load_state_dict(checkpoint["scaler_state_dict"])
        start_epoch = int(checkpoint.get("epoch", -1)) + 1
        best_value = float(checkpoint.get("best_value", best_value))
        if is_main(rank):
            print(f"[RESUME] {args.resume} epoch={start_epoch} best={best_value}")

    history_path = os.path.join(args.output_dir, "history.csv")
    for epoch in range(start_epoch, args.epochs):
        if train_sampler is not None:
            train_sampler.set_epoch(epoch)
        if val_sampler is not None:
            val_sampler.set_epoch(epoch)
        start = time.time()
        train_metrics = run_epoch(
            model, train_loader, loss_cfg, device, world, True,
            optimizer, scheduler, scaler, args, epoch, rank,
        )
        val_metrics = run_epoch(
            model, val_loader, loss_cfg, device, world, False,
            None, None, scaler, args, epoch, rank,
        )

        if is_main(rank):
            row: Dict[str, Any] = {"epoch": epoch, "elapsed_sec": time.time() - start}
            row.update({f"train/{k}": v for k, v in train_metrics.items()})
            row.update({f"val/{k}": v for k, v in val_metrics.items()})
            row["lr"] = optimizer.param_groups[0]["lr"]
            append_history(history_path, row)

            metric_key = args.best_metric
            if metric_key not in val_metrics:
                raise KeyError(
                    f"best_metric={metric_key!r} not found. Available: {sorted(val_metrics)}"
                )
            current = float(val_metrics[metric_key])
            improved = current > best_value if args.best_mode == "max" else current < best_value
            if improved:
                best_value = current
                save_checkpoint(
                    os.path.join(args.output_dir, "best.tar"),
                    model, optimizer, scheduler, scaler, epoch, best_value,
                    scorer_cfg, loss_cfg, schema, args,
                )
            if (epoch + 1) % max(args.save_every, 1) == 0:
                save_checkpoint(
                    os.path.join(args.output_dir, f"epoch_{epoch:03d}.tar"),
                    model, optimizer, scheduler, scaler, epoch, best_value,
                    scorer_cfg, loss_cfg, schema, args,
                )
            save_checkpoint(
                os.path.join(args.output_dir, "latest.tar"),
                model, optimizer, scheduler, scaler, epoch, best_value,
                scorer_cfg, loss_cfg, schema, args,
            )
            print(
                f"[EPOCH {epoch:03d}] train_loss={train_metrics.get('loss/total', float('nan')):.4f} "
                f"val_loss={val_metrics.get('loss/total', float('nan')):.4f} "
                f"val_top10U={val_metrics.get('metric/top10_utility', float('nan')):.4f} "
                f"val_invalid10={val_metrics.get('metric/top10_invalid', float('nan')):.4f} "
                f"best={best_value:.4f}",
                flush=True,
            )
        if world > 1:
            dist.barrier()

    if world > 1:
        dist.destroy_process_group()


if __name__ == "__main__":
    main()
